name: vsartist
description: Artist application for vibespot music player.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.4+7

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  http: ^0.12.0+2
  sqflite: ^1.1.5
  path_provider: ^1.3.0
  rxdart: ^0.22.0
  connectivity: ^0.4.3+1
  shared_preferences: ^0.5.3+4
  image_picker: ^0.6.1+4
  bloc: ^0.14.1
  flutter_bloc: ^0.14.0
  file_picker: ^1.4.3+2
  flutter_date_picker: ^0.1.8
  datetime_picker_formfield: ^0.2.0
  dio: ^3.0.8
  flutter_paystack: ^1.0.1
  url_launcher: ^5.4.1
  # toast: ^0.1.4
  fluttertoast: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
   - assets/images/splash.png
   - assets/images/vibeStream-selected-icon.png
   - assets/images/logo-200.png
   - assets/images/vibeStream-white-icon.png
   - assets/images/splash-background.png
   - assets/images/user-avatar.png
   - assets/images/vibe-logo-on-splash-background.png
   - assets/images/vibe-logo-on-black.png
   - assets/images/create-account-btn.png
   - assets/images/signin-btn.png
   - assets/images/email-btn.png
   - assets/images/facebook-btn.png
   - assets/images/google-btn.png
   - assets/images/email-icon.png
   - assets/images/facebook-white-logo.png
   - assets/images/google-white-logo.png
   - assets/images/mySpot-selected-icon.png
   - assets/images/vibeStream-selected-icon.png
   - assets/images/vibespot-appicon2x.png
   - assets/images/no-data-image.png
   - assets/images/shopping-cart-icon.png
   - assets/images/shape2-icon.png
   - assets/images/add-plus-icon.png
   - assets/images/successful-payment.png
   - assets/images/myAccount-selected-icon.png
   - assets/images/icons/vibespot_app-xx.png

   # For onboarding screens
   - assets/images/onboard/manage-profile.png
   - assets/images/onboard/fan-base.png
   - assets/images/onboard/statistics.png
   - assets/images/onboard/partnership.png

   - assets/datas/states.json
   - assets/datas/cities.json
   - assets/datas/local_governments.json

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-BlackItalic.ttf
        - asset: assets/fonts/Poppins-BoldItalic.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-LightItalic.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-MediumItalic.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
          style: italic

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
